## Imports

In [1]:
import numpy as np
import pandas as pd
import csv

## Working with the csv

In [2]:
words = []
with open("store_data.csv", mode='r') as data:
    raw_data = csv.reader(data, delimiter=',')
    for row in raw_data:
        words.extend(row)

In [3]:
words = list(set(words))
print(len(words))

120

In [4]:
words

['protein bar',
 'pepper',
 'extra dark chocolate',
 'milk',
 'butter',
 'tomato juice',
 'olive oil',
 'strawberries',
 'almonds',
 'gluten free bar',
 'pancakes',
 'herb & pepper',
 'salad',
 'sandwich',
 'pasta',
 'turkey',
 'cooking oil',
 'oil',
 'frozen smoothie',
 'bacon',
 'yogurt cake',
 'cider',
 'black tea',
 'ground beef',
 'ham',
 'soda',
 'corn',
 ' asparagus',
 'antioxydant juice',
 'nonfat milk',
 'salt',
 'napkins',
 'shallot',
 'fromage blanc',
 'mint green tea',
 'energy drink',
 'cake',
 'bug spray',
 'chocolate bread',
 'frozen vegetables',
 'tomatoes',
 'hand protein bar',
 'grated cheese',
 'salmon',
 'cookies',
 'strong cheese',
 'spinach',
 'eggplant',
 'burger sauce',
 'fresh tuna',
 'mushroom cream sauce',
 'brownies',
 'green grapes',
 'eggs',
 'low fat yogurt',
 'pickles',
 'barbecue sauce',
 'tea',
 'flax seed',
 'red wine',
 'green tea',
 'zucchini',
 'blueberries',
 'water spray',
 'ketchup',
 'bramble',
 'gums',
 'magazines',
 'muffins',
 'burgers',
 'french wine',
 'cream',
 'tomato sauce',
 'chocolate',
 'carrots',
 'asparagus',
 'whole weat flour',
 'spaghetti',
 'mashed potato',
 'energy bar',
 'green beans',
 'whole wheat rice',
 'sparkling water',
 'escalope',
 'cauliflower',
 'pet food',
 'babies food',
 'clothes accessories',
 'champagne',
 'body spray',
 'cereals',
 'honey',
 'mayonnaise',
 'yams',
 'meatballs',
 'whole wheat pasta',
 'vegetables mix',
 'hot dogs',
 'mineral water',
 'shampoo',
 'light cream',
 'candy bars',
 'cottage cheese',
 'melons',
 'rice',
 'soup',
 'avocado',
 'french fries',
 'oatmeal',
 'chutney',
 'shrimp',
 'chili',
 'toothpaste',
 'fresh bread',
 'chicken',
 'parmesan cheese',
 'light mayo',
 'mint',
 'white wine',
 'dessert wine']

In [5]:
dic = [{i:0 for i in words}]*7501

## Dataframe from the csv

In [6]:
df = pd.read_csv("store_data.csv", header=None)

## Dataframe of the coded form

In [7]:
dft = pd.DataFrame(dic, columns = words)
dft

,protein bar,pepper,extra dark chocolate,milk,butter,tomato juice,olive oil,strawberries,almonds,gluten free bar,...,shrimp,chili,toothpaste,fresh bread,chicken,parmesan cheese,light mayo,mint,white wine,dessert wine
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
for i in range(7501):
    row_1 = df.iloc[i]
    for j in row_1:
        dft.iloc[i][j] = 1

In [9]:
dft

,protein bar,pepper,extra dark chocolate,milk,butter,tomato juice,olive oil,strawberries,almonds,gluten free bar,...,shrimp,chili,toothpaste,fresh bread,chicken,parmesan cheese,light mayo,mint,white wine,dessert wine
0,0,0,0,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Stats

In [10]:
from mlxtend.frequent_patterns import apriori, association_rules

In [11]:
freq_itemsets = apriori(dft, min_support=0.01, use_colnames=True)
freq_itemsets

      support                                  itemsets
0    0.018531                             (protein bar)
1    0.026530                                  (pepper)
2    0.011998                    (extra dark chocolate)
3    0.129583                                    (milk)
4    0.030129                                  (butter)
..        ...                                       ...
252  0.010532              (eggs, chocolate, spaghetti)
253  0.013465          (chocolate, mineral water, eggs)
254  0.014265          (eggs, mineral water, spaghetti)
255  0.015865     (chocolate, mineral water, spaghetti)
256  0.010132  (mineral water, spaghetti, french fries)

[257 rows x 2 columns]

In [12]:
rules = association_rules(freq_itemsets, metric='confidence', min_threshold=0.5)
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(milk, ground beef)",(mineral water),0.021997,0.238368,0.011065,0.503030,2.110308,0.005822,1.532552
1,"(ground beef, eggs)",(mineral water),0.019997,0.238368,0.010132,0.506667,2.125563,0.005365,1.543848

In [13]:
rules[(rules['lift'] > 1.2) & (rules['confidence'] > 0.5)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(milk, ground beef)",(mineral water),0.021997,0.238368,0.011065,0.503030,2.110308,0.005822,1.532552
1,"(ground beef, eggs)",(mineral water),0.019997,0.238368,0.010132,0.506667,2.125563,0.005365,1.543848